import 'package:flutter/material.dart';

abstract final class NotesTheme {
  static ThemeData light() => _build(
        brightness: Brightness.light,
        primary: const Color(0xFF3559E0),
        onPrimary: Colors.white,
        primaryContainer: const Color(0xFFE1E7FF),
        onPrimaryContainer: const Color(0xFF182B75),
        secondary: const Color(0xFF69574B),
        secondaryContainer: const Color(0xFFF0E4D9),
        onSecondaryContainer: const Color(0xFF34281F),
        scaffold: const Color(0xFFF6F4EF),
        surface: const Color(0xFFFFFDFA),
        onSurface: const Color(0xFF17212B),
        surfaceContainer: const Color(0xFFF0EEE8),
        surfaceContainerLow: const Color(0xFFF9F7F2),
        surfaceContainerHigh: const Color(0xFFEAE7E0),
        onSurfaceVariant: const Color(0xFF555D65),
        outline: const Color(0xFF777D84),
        outlineVariant: const Color(0xFFDCDAD3),
      );

  static ThemeData dark() => _build(
        brightness: Brightness.dark,
        primary: const Color(0xFFADBEFF),
        onPrimary: const Color(0xFF14276C),
        primaryContainer: const Color(0xFF293C79),
        onPrimaryContainer: const Color(0xFFE1E7FF),
        secondary: const Color(0xFFDFC1A9),
        secondaryContainer: const Color(0xFF44382F),
        onSecondaryContainer: const Color(0xFFF1DDCD),
        scaffold: const Color(0xFF111820),
        surface: const Color(0xFF1B2632),
        onSurface: const Color(0xFFF0F3F7),
        surfaceContainer: const Color(0xFF19232E),
        surfaceContainerLow: const Color(0xFF16202A),
        surfaceContainerHigh: const Color(0xFF26323E),
        onSurfaceVariant: const Color(0xFFBDC7D1),
        outline: const Color(0xFF8B98A5),
        outlineVariant: const Color(0xFF3A4754),
      );

  static ThemeData _build({
    required Brightness brightness,
    required Color primary,
    required Color onPrimary,
    required Color primaryContainer,
    required Color onPrimaryContainer,
    required Color secondary,
    required Color secondaryContainer,
    required Color onSecondaryContainer,
    required Color scaffold,
    required Color surface,
    required Color onSurface,
    required Color surfaceContainer,
    required Color surfaceContainerLow,
    required Color surfaceContainerHigh,
    required Color onSurfaceVariant,
    required Color outline,
    required Color outlineVariant,
  }) {
    final scheme = ColorScheme(
      brightness: brightness,
      primary: primary,
      onPrimary: onPrimary,
      primaryContainer: primaryContainer,
      onPrimaryContainer: onPrimaryContainer,
      secondary: secondary,
      onSecondary: brightness == Brightness.light ? Colors.white : const Color(0xFF3A2C23),
      secondaryContainer: secondaryContainer,
      onSecondaryContainer: onSecondaryContainer,
      tertiary: primary,
      onTertiary: onPrimary,
      error: brightness == Brightness.light ? const Color(0xFFBA1A1A) : const Color(0xFFFFB4AB),
      onError: brightness == Brightness.light ? Colors.white : const Color(0xFF690005),
      surface: surface,
      onSurface: onSurface,
      surfaceContainer: surfaceContainer,
      surfaceContainerLow: surfaceContainerLow,
      surfaceContainerHigh: surfaceContainerHigh,
      onSurfaceVariant: onSurfaceVariant,
      outline: outline,
      outlineVariant: outlineVariant,
      shadow: Colors.black,
      scrim: Colors.black,
      inverseSurface: onSurface,
      onInverseSurface: surface,
      inversePrimary: primaryContainer,
      surfaceTint: primary,
    );

    final base = ThemeData(brightness: brightness, useMaterial3: true);
    return base.copyWith(
      colorScheme: scheme,
      scaffoldBackgroundColor: scaffold,
      canvasColor: scaffold,
      cardColor: surface,
      dividerColor: outlineVariant,
      textTheme: base.textTheme.copyWith(
        displayMedium: const TextStyle(fontFamily: 'serif', fontWeight: FontWeight.w500, fontSize: 48, height: 56 / 48),
        headlineLarge: const TextStyle(fontFamily: 'serif', fontWeight: FontWeight.w500, fontSize: 36, height: 42 / 36),
        headlineMedium: const TextStyle(fontFamily: 'serif', fontWeight: FontWeight.w500, fontSize: 30, height: 36 / 30),
        headlineSmall: const TextStyle(fontFamily: 'serif', fontWeight: FontWeight.w500, fontSize: 25, height: 32 / 25),
        titleLarge: const TextStyle(fontWeight: FontWeight.w600, fontSize: 22, height: 28 / 22),
        titleMedium: const TextStyle(fontWeight: FontWeight.w600, fontSize: 18, height: 25 / 18),
        bodyLarge: const TextStyle(fontSize: 17, height: 27 / 17),
        bodyMedium: const TextStyle(fontSize: 15, height: 23 / 15),
      ),
      cardTheme: CardThemeData(
        color: surface,
        elevation: 0,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24), side: BorderSide(color: outlineVariant)),
      ),
      navigationBarTheme: NavigationBarThemeData(
        elevation: 0,
        backgroundColor: surface,
        indicatorColor: primaryContainer,
        labelTextStyle: WidgetStateProperty.resolveWith(
          (states) => TextStyle(
            color: states.contains(WidgetState.selected) ? primary : onSurfaceVariant,
            fontSize: 12,
          ),
        ),
      ),
      appBarTheme: AppBarTheme(backgroundColor: scaffold, foregroundColor: onSurface, elevation: 0, surfaceTintColor: Colors.transparent),
      floatingActionButtonTheme: FloatingActionButtonThemeData(
        backgroundColor: primary,
        foregroundColor: onPrimary,
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20)),
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: surface,
        border: OutlineInputBorder(borderRadius: BorderRadius.circular(20)),
        enabledBorder: OutlineInputBorder(borderRadius: BorderRadius.circular(20), borderSide: BorderSide(color: outlineVariant)),
      ),
    );
  }
}
